2024-02-12 19:32:36,697 INFO    MainThread:56685 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-12 19:32:36,698 INFO    MainThread:56685 [wandb_setup.py:_flush():76] Configure stats pid to 56685
2024-02-12 19:32:36,698 INFO    MainThread:56685 [wandb_setup.py:_flush():76] Loading settings from /home-nfs/fx2024/.config/wandb/settings
2024-02-12 19:32:36,698 INFO    MainThread:56685 [wandb_setup.py:_flush():76] Loading settings from /home-nfs/fx2024/NLP/NLP/wandb/settings
2024-02-12 19:32:36,698 INFO    MainThread:56685 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-12 19:32:36,698 INFO    MainThread:56685 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-12 19:32:36,698 INFO    MainThread:56685 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home-nfs/fx2024/NLP/NLP/main.py', 'program': '/home-nfs/fx2024/NLP/NLP/main.py'}
2024-02-12 19:32:36,698 INFO    MainThread:56685 [wandb_init.py:_log_setup():526] Logging user logs to /home-nfs/fx2024/NLP/NLP/wandb/run-20240212_193236-test/logs/debug.log
2024-02-12 19:32:36,698 INFO    MainThread:56685 [wandb_init.py:_log_setup():527] Logging internal logs to /home-nfs/fx2024/NLP/NLP/wandb/run-20240212_193236-test/logs/debug-internal.log
2024-02-12 19:32:36,698 INFO    MainThread:56685 [wandb_init.py:init():566] calling init triggers
2024-02-12 19:32:36,699 INFO    MainThread:56685 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'architecture': 'GPT2', 'dataset': 'wikitext', 'epochs': 5}
2024-02-12 19:32:36,699 INFO    MainThread:56685 [wandb_init.py:init():616] starting backend
2024-02-12 19:32:36,699 INFO    MainThread:56685 [wandb_init.py:init():620] setting up manager
2024-02-12 19:32:36,701 INFO    MainThread:56685 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-12 19:32:36,704 INFO    MainThread:56685 [wandb_init.py:init():628] backend started and connected
2024-02-12 19:32:36,713 INFO    MainThread:56685 [wandb_init.py:init():720] updated telemetry
2024-02-12 19:32:36,727 INFO    MainThread:56685 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-12 19:32:36,949 ERROR   MainThread:56685 [wandb_init.py:init():779] encountered error: You provided an invalid value for the `resume` argument. The value 'never' is not a valid option for resuming a run (test) that already exists. Please check your inputs and try again with a valid value for the `resume` argument.
2024-02-12 19:32:37,047 ERROR   MainThread:56685 [wandb_init.py:init():1194] You provided an invalid value for the `resume` argument. The value 'never' is not a valid option for resuming a run (test) that already exists. Please check your inputs and try again with a valid value for the `resume` argument.
Traceback (most recent call last):
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.UsageError: You provided an invalid value for the `resume` argument. The value 'never' is not a valid option for resuming a run (test) that already exists. Please check your inputs and try again with a valid value for the `resume` argument.
2024-02-12 19:32:38,052 WARNING MsgRouterThr:56685 [router.py:message_loop():77] message_loop has been closed
