Traceback (most recent call last):
  File "/home-nfs/fx2024/NLP/NLP/main.py", line 344, in <module>
    gpt_finetune(args, model)
  File "/home-nfs/fx2024/NLP/NLP/main.py", line 101, in gpt_finetune
    all_indices = list(range(len(dataset)))
                             ^^^^^^^^^^^^
  File "/home-nfs/fx2024/NLP/NLP/my_dataset.py", line 24, in __len__
    return len(self.X.num_rows)
               ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'num_rows'