2024-02-12 20:28:26,106 INFO    StreamThr :68087 [internal.py:wandb_internal():86] W&B internal server running at pid: 68087, started at: 2024-02-12 20:28:26.104355
2024-02-12 20:28:26,108 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: status
2024-02-12 20:28:26,115 INFO    WriterThread:68087 [datastore.py:open_for_write():87] open: /home-nfs/fx2024/NLP/NLP/wandb/run-20240212_202826-test/run-test.wandb
2024-02-12 20:28:26,117 DEBUG   SenderThread:68087 [sender.py:send():382] send: header
2024-02-12 20:28:26,130 DEBUG   SenderThread:68087 [sender.py:send():382] send: run
2024-02-12 20:28:26,298 ERROR   SenderThread:68087 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:28:26,298 ERROR   SenderThread:68087 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:28:27,444 ERROR   SenderThread:68087 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:28:27,444 ERROR   SenderThread:68087 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:28:29,513 ERROR   SenderThread:68087 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:28:29,514 ERROR   SenderThread:68087 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:28:29,514 INFO    SenderThread:68087 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-02-12 20:28:31,131 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:28:34,118 ERROR   SenderThread:68087 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:28:34,118 ERROR   SenderThread:68087 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:28:36,133 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:28:41,135 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:28:42,265 ERROR   SenderThread:68087 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:28:42,265 ERROR   SenderThread:68087 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:28:46,137 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:28:51,138 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:28:56,140 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:29:00,159 ERROR   SenderThread:68087 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:29:00,159 ERROR   SenderThread:68087 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:29:01,141 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:29:06,143 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:29:11,145 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:29:16,147 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:29:21,148 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:29:26,150 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:29:31,152 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:29:33,959 ERROR   SenderThread:68087 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:29:33,960 ERROR   SenderThread:68087 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:29:36,158 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:29:41,160 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:29:46,162 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:29:51,164 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:29:56,165 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: cancel
2024-02-12 20:29:56,166 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: cancel
2024-02-12 20:29:56,167 DEBUG   SenderThread:68087 [sender.py:send():391] Record cancelled: run
2024-02-12 20:29:56,167 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: status_report
2024-02-12 20:29:56,283 DEBUG   HandlerThread:68087 [handler.py:handle_request():146] handle_request: shutdown
2024-02-12 20:29:56,283 INFO    HandlerThread:68087 [handler.py:finish():869] shutting down handler
2024-02-12 20:29:57,167 INFO    SenderThread:68087 [sender.py:finish():1572] shutting down sender
2024-02-12 20:29:57,168 INFO    WriterThread:68087 [datastore.py:close():296] close: /home-nfs/fx2024/NLP/NLP/wandb/run-20240212_202826-test/run-test.wandb
